import React from 'react'

const Policy = () => {
    return (
        <section className="min-h-screen flex justify-center items-center py-12">
            <div className="max-w-5xl ">
                <h2 className="text-4xl text-primary font-bold text-center">Privacy Policy & Terms Of Service</h2>
                <div className="py-7"><p className="text-lg text-slate-500 text-justify"><span className="text-bold pb-4">Welcome to HelpStudyAbroad.com</span></p>
                    <h3 className="text-4xl text-slate-600 font-bold py-7">1. General</h3>
                    <p className="text-lg text-slate-500 text-justify">If you continue to browse and use this website you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern WAYGOOD EDTECH PRIVATE LIMITED relationship with you in relation to this website/mobile and the product which you purchase through this website/mobile. The term &apos;WAYGOOD EDTECH PRIVATE LIMITED&apos; or &apos;HelpStudyAbroad.com, or &apos;us&apos; or &apos;we&apos; refers to the owner of the website/mobile. The term &apos;you&apos; refers to the user/viewer of our website.
                        This Agreement is an electronic record in terms of Information Technology Act, 2000, and generated by a computer system and does not require any physical or digital signatures.
                    </p>
                    <h3 className="text-4xl text-slate-600 font-bold py-7">2. About Us</h3>
                    <p className="text-xl text-slate-500 font-semibold">The use of this platform and the products purchased on this platform is subject to the following terms of use:</p>
                    <ol className='text-lg text-slate-500 list-decimal'>
                        <li>The content of the pages of this platform is for your general information and use only. It is subject to change without notice.
                        </li>
                        <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this platform for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
                        </li>
                        <li>Your use of any information or materials on this platform is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products or information available through this platform meet your specific requirements.
                        </li>
                        <li>This platform contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.
                        </li>
                        <li>All trademarks reproduced in this platform which are not the property of, or licensed to, the operators are acknowledged on the website. No use of the intellectual property owned or licensed to WAYGOOD EDTECH PRIVATE LIMITED may be used without our prior written authorization.
                        </li>
                        <li>Unauthorised use of this platform may give rise to a claim for damages and/or be a criminal offence.</li>
                        <li>From time to time this platform may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).
                        </li>
                        <li>You may not create a link to this website from another platform any other lead source, or document without WAYGOOD EDTECH PRIVATE LIMITED prior written consent.
                        </li>
                        <li>Your use of this platform and any dispute arising out of such use of the platform is subject to the laws of India or other regulatory authority.
                        </li>
                        <li>Your use of our products and services provided for herein is solely for your personal and non-commercial use. Any use other than for personal purposes is prohibited. Your personal and non-commercial use of our services shall be subjected to the following restrictions: i) You may not decompile, reverse engineer, or disassemble the contents of our products, or (c) remove any copyright, trademark registration, or other proprietary notices from the contents of our products. ii) You will not (a) use our product or service for commercial purposes of any kind, or (b) advertise or sell any products, services or otherwise (whether or not for profit), or solicit others (including, without limitation, solicitations for contributions or donations) or use any public forum for commercial purposes of any kind, or (c) use our products and services in any way that is unlawful, or harms WAYGOOD EDTECH PRIVATE LIMITED  or any other person or entity as determined by WAYGOOD EDTECH PRIVATE LIMITED .
                        </li>
                        <li>WAYGOOD EDTECH PRIVATE LIMITED products and / or services, including the WAYGOOD EDTECH PRIVATE LIMITED application and content, may not be compatible to all devices. WAYGOOD EDTECH PRIVATE LIMITED shall not be obligated to provide workable products and / or services for any phones/tablets unless stated otherwise.
                        </li>
                        <li>WAYGOOD EDTECH PRIVATE LIMITED or any of its subsidiaries or content partners shall have no responsibility for any loss or damage caused to tablet or phone or any other hardware and / or software, including loss of data or effect on the processing speed of the tablet, those results from the use of our products and services.
                        </li>
                        <li>In no event will WAYGOOD EDTECH PRIVATE LIMITED. be liable for damages of any kind, including without limitation, (i) indirect, punitive, special, exemplary, incidental, or consequential damage (including loss of business, revenue, profits, use, data or other economic advantage, loss of programs or information), or (ii) direct damages in excess of the amount paid to WAYGOOD EDTECH PRIVATE LIMITED  for the product and / or service, arising out of the use of, misuse of or inability to use, or errors, omissions or other inaccuracies in the Site or the products and / or services, or any information provided on the Site. Some jurisdictions do not allow the limitation or exclusion of liability. Accordingly, in such instances, some of the above limitations may not apply to the User.
                        </li>
                        <li>WAYGOOD EDTECH PRIVATE LIMITED may also contact the user through SMS, email and call to give notifications on various important updates. Therefore, User holds WAYGOOD EDTECH PRIVATE LIMITED non liable to any liabilities including financial penalties, damages, expenses in case the users’ mobile number is registered with Do not Call (DNC) database.
                        </li>
                        <li>You hereby indemnify, defend, and hold WAYGOOD EDTECH PRIVATE LIMITED distributors, agents, representatives and other authorised users, and each of the foregoing entities” respective resellers, distributors, service providers and suppliers, and all of the foregoing entities’ respective officers, directors, owners, employees, agents, representatives, harmless from and against any and all losses, damages, liabilities and costs arising from your use of our product.
                        </li>
                        <li>In the event of breach of the terms and conditions of this Terms of Use by the User, the User shall be promptly liable to indemnify WAYGOOD EDTECH PRIVATE LIMITED for all the costs, losses and damages caused to WAYGOOD EDTECH PRIVATE LIMITED because of such a breach.
                        </li>
                        <li>In the event of your breach of this Terms of Use, you agree that WAYGOOD EDTECH PRIVATE LIMITED will be irreparably harmed and will not have an adequate remedy in money or damages. WAYGOOD EDTECH PRIVATE LIMITED therefore, shall be entitled in such event to obtain an injunction against such a breach from any court of competent jurisdiction immediately upon request. WAYGOOD EDTECH PRIVATE LIMITED right to obtain such relief shall not limit its right to obtain other remedies.
                        </li>
                        <li>Persons who are “competent/capable” of contracting within the meaning of the Indian Contract Act, 1872 shall be eligible to use our products or services. Persons who are minors, un-discharged insolvents etc. are not eligible to use our products or services. As a minor if you wish to use our products or services, such use shall be made available to you by your legal guardian or parents. WAYGOOD EDTECH PRIVATE LIMITED will not be responsible for any consequence that arises as a result of misuse of any kind of our products or services that may occur by virtue of any person including a minor using the services provided. By using the products or services you warrant that all the data provided by you is accurate and complete and that you have obtained the consent of parent/legal guardian (in case of minors). WAYGOOD EDTECH PRIVATE LIMITED reserves the right to terminate your subscription and / or refuse to provide you with access to the products or services if it is discovered that you are under the age of 18 years and the consent to use the products or services is not made by your parent/legal guardian or any information provided by you is inaccurate.
                        </li>
                        <li>The users of this platform shall not host, display, upload, modify, publish, transmit, update or share any information that:
                            <ul className='list-disc'>
                                <li>to another person and to which the user does not have any right to;
                                </li>
                                <li>is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
                                </li>
                                <li>harm minors in any way;</li>
                                <li>infringes any patent, trademark, copyright or other proprietary rights;
                                </li>
                                <li>violates any law for the time being in force;
                                </li>
                                <li>deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;

                                </li>
                                <li>impersonate another person;</li>
                                <li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;
                                </li>
                                <li>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.
                                </li>
                            </ul>
                        </li>
                        <li>We respect your right to privacy in respect of any personal information provided to us. To see how we collect and use your personal information, please see our Privacy Policy. The Privacy Policy is a necessary part of this Terms and Conditions and the clauses therein are not repeated here for the sake of brevity.
                        </li>
                        <li>We will not be liable for any non-compliance or delay in compliance with any of the obligations we assume under any contract when caused by events that are beyond our reasonable control or on account of force majeure.
                        </li>
                    </ol>
                    <h3 className="text-4xl text-slate-600 font-bold py-7">3. Term & Termination</h3>
                    <p className="text-lg text-slate-500 text-justify">This Agreement will remain in full force and effect until terminated, for using the platform or purchasing the products in any form or capacity. Provided, we have the right to immediately terminate your access or usage and remove non-compliant information or material, in case of non-compliance with the terms and conditions or our privacy policy
                        The User shall be obligated to clear any dues with us for any of its Services which you have procured. WAYGOOD EDTECH PRIVATE LIMITED shall not be liable to you or any third party for any termination of your access to the Services.

                    </p>
                    <h3 className="text-4xl text-slate-600 font-bold py-7">4. Governing Law</h3>
                    <p className="text-lg text-slate-500 text-justify">The jurisdictional court of New Delhi, India shall have sole jurisdiction over any claim arising from, or related to, a visit to / use of the platform or purchase of the products. In case you are from a different country, we retain the right to bring proceedings against you for breach of any of the terms and conditions in your country of residence, country of use or other relevant country. The laws of New Delhi, India govern this Agreement and these terms and conditions of use of the platform or purchase of the products.
                        <br />WAYGOOD EDTECH PRIVATE LIMITED accepts no liability whatsoever, direct or indirect, for non-compliance with the laws of any country other than that of India, and the mere fact that the platform can be accessed or used in a country other than India will not imply that we accede to the laws of such country.</p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">5. Contact Us</h3>
                    <p className="text-lg text-slate-500 text-justify">If you have any questions or complaints about the online training package, the platform and their contents please contact us at grievance@leverageedu.com.</p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">6. HelpStudyAbroad.com Terms & Conditions</h3>
                    <p className="text-lg text-slate-500 text-justify">The student agrees to authorise Waygood EdTech as his/her agent and help with his/her applications & other admission related services.
                        The student agrees to change his/her agent to Waygood EdTech in case there is another agent already authorised prior to this.
                    </p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">7. Waygood EdTech Scholarship Terms & Conditions</h3>
                    <p className="text-lg text-slate-500 text-justify">The reward will be processed once you pay the deposit at the university and receive your Visa
                        The scholarship amount is to be determined on the basis of your application and overall profile
                        Selection for the scholarship to be solely at the discretion of the Waygood EdTech jury and corresponding guidelines

                    </p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">8. Inbox</h3>
                    <p className="text-lg text-slate-500 text-justify">We create custom email IDs to enhance your overall study abroad journey. This ID is used to submit and track your applications to global universities. Alongside, you can receive the latest updates regarding intakes and candidature from top university representatives. Visit the Inbox section in your dashboard or on the app to view and reply to university emails. Waygood EdTech has “read-only” access which is used to provide real time updates across all your applications and make your study abroad journey hassle-free. Waygood EdTech will not reply to or communicate with the university or any other entity through your ID. Through this email id, we would not be accessing or sending to any third party, any of your personal information without your consent.
                    </p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">9. Handling of Student Financial Awards
                    </h3>
                    <p className="text-lg text-slate-500 text-justify">Waygood EdTech does not collect any remuneration from students that is conditional upon the receipt of scholarships and financial aid monies awarded by partner institutions, or other scholarship awarding organizations.
                    </p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">10. Company Details
                    </h3>
                    <p className="text-lg text-slate-500 text-justify">UK registration number - 13642985
                        <br />VAT number - 408 8726 70
                    </p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">11. Payments
                    </h3>
                    <p className="text-lg text-slate-500 text-justify">We do not require you to make payments for any purposes in any individual’s bank accounts. Any payments for any purpose including purposes of applications, deposit, tuition fee payments or to purchase any service packages offered by Leverage must be made through the official Leverage payment channels or specific university payment accounts, as the case maybe.
                    </p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">12. Educational Finance and Services
                    </h3>
                    <p className="text-lg text-slate-500 text-justify">We are not a financial institution. We are education experts who as part of your education counselling advice and comments based on our knowledge and experience with several students like yours. We partner with banks, NBFCs and other financial institutions to provide you specific finance advisory and or education loan as and when needed. We try best to partner with trusted and reputed organization and companies to provide you effective service. However, we will not be liable for any false advisory, non-compliance or delay in compliance with any of the obligations our partner organizations assume under any contract when caused by events that are beyond our reasonable control or on account of force majeure
                    </p>

                    <h3 className="text-4xl text-slate-600 font-bold py-7">13. Waygood EdTech Global Study Abroad Scholarship
                    </h3>
                    <p className="text-lg text-slate-500 text-justify">For additional T&Cs related to Waygood EdTech Study Abroad Scholarship programme, please check the scholarship page T&C                    </p>

                    </div>
            </div>
        </section>
    )
}

export default Policy
